[Variables]
Author=LINK

;How to edit dock
;First paste your favorite icons here [Documents\Rainmeter\Skins\Windows 20 StartMenu\@Resources\Icons]
;Then type the icon name in Dock 1, Dock 2, etc. below
;Then paste the location path of the application on LocationPath1, LocationPath2 etc.
;Use Icon pixel less then 60*60
___________________Taskbar___________________

Taskbar Dock 1=File
Taskbar Location Path1=[Shell:::{20D04FE0-3AEA-1069-A2D8-08002B30309D}]

Taskbar Dock 2=Mail
Taskbar Location Path2=["https://mail.google.com/mail/"]

Taskbar Dock 3=Microsoft Edge
Taskbar Location Path3=["#@#\Application\Microsoft Edge"]

Taskbar Dock 4=Microsoft Store
Taskbar Location Path4=["#@#\Application\Microsoft Store"]

Taskbar Dock 5=Brave
Taskbar Location Path5=brave.exe

Taskbar Dock 6=photoshop
Taskbar Location Path6=Photoshop.exe

___________________Start Menu Application Line 1___________________

Dock 1=Microsoft Store
LocationPath1=["#@#\Application\Microsoft Store"]

Dock 2=Calendar
LocationPath2=["#@#\Application\Calendar"]

Dock 3=Calculator
LocationPath3=["#@#\Application\Calculator"]

Dock 4=Photos
LocationPath4=["#@#\Application\Photos"]

Dock 5=Microsoft Paint
LocationPath5=mspaint.exe

___________________Start Menu Application Line 2___________________

Dock 6=Documents
LocationPath6=[Shell:::{A8CDFF1C-4878-43be-B5FD-F8091C1C60D0}]

Dock 7=Downloads
LocationPath7=[Shell:::{374DE290-123F-4565-9164-39C4925E467B}]

Dock 8=Videos
LocationPath8=[Shell:::{A0953C92-50DC-43bf-BE83-3742FED03C9C}]

Dock 9=Recycle Bin
LocationPath9=[Shell:::{645FF040-5081-101B-9F08-00AA002F954E}]

Dock 10=Computer
LocationPath10=[Shell:::{20D04FE0-3AEA-1069-A2D8-08002B30309D}]

___________________Start Menu Application Line 3___________________
Dock 11=Movies and TV
LocationPath11=["#@#\Application\Movies & TV"]

Dock 12=Mail
LocationPath12=["https://mail.google.com/mail/"]

Dock 13=Microsoft Edge
LocationPath13=msedge.exe

Dock 14=Skype
LocationPath14=["#@#\Application\Skype"]

Dock 15=Twitter
LocationPath15=["https://twitter.com/?lang=en"]

___________________Start Menu Application Line 4___________________

Dock 16=Discord
LocationPath16=Discord.exe

Dock 17=Facebook
LocationPath17="[https://www.facebook.com/"]

Dock 18=telegram
LocationPath18=telegram.exe

Dock 19=Groove Music
LocationPath19=["#@#\Application\Groove Music"]

Dock 20=spotify
LocationPath20=

___________________Start Menu Application Line 5___________________

Dock 21=Paint 3D
LocationPath21=["#@#\Application\Paint 3D"]

Dock 22=Brave
LocationPath22=brave.exe

Dock 23=Microsoft Paint
LocationPath23=

Dock 24=Notepad
LocationPath24=notepad.exe

Dock 25=chrome
LocationPath25=chrome.exe

___________________Start Menu Application Line 6___________________

Dock 26=Camera
LocationPath26=

Dock 27=Windows Defender
LocationPath27=["#@#\Application\Windows Security"]

Dock 28=photoshop
LocationPath28=Photoshop.exe

Dock 29=Sticky Notes
LocationPath29=["#@#\Application\Sticky Notes"]

Dock 30=Settings
LocationPath30=[Shell:::{5399E694-6CE5-4D6C-8FCE-1D8870FDCBA0}]

