[Variables]

Language=English
TempSymbol=C
MeasureName2=MeasureTempCelsius
Color1=69,69,69,235
Color2=180,223,250
Color3=0,0,0
GradientOpacity=0
GradientColor=255,255,255

;Toggle Icon and Text Change Value=1
Hidden=0

ScrollMouseIncrement=6.11
ScrollMouseIncrement2=50

Player=WMP
;-------------------------------------------------------------
;-------------------------------------------------------------

Icon1NameAndPath=#@#\spotify.png
TextName1=spotify
LocationPath1=["C:\Users\USERNAME\AppData\Roaming\Spotify"]

Icon2NameAndPath=#@#\netflix.png
TextName2=netflix
LocationPath2=["https://netflix.com"]

Icon3NameAndPath=#@#\photoshop.png
TextName3=photoshop
LocationPath3=["C:\Users\USERNAME\AppData\Roaming\photoshop"]

;-------------------------------------------------------------
;--System-----------------------------------------------------
;-------------------------------------------------------------


fontName=Trebuchet MS
textSize=8
colorText=69,69,69,205
colorLine=69,69,69,25
heightBar=1

[styleLeftText]
; Meters using styleLeftText will be left-aligned.
StringAlign=Left
StringCase=None
StringStyle=Bold
StringEffect=Shadow
FontEffectColor=0,0,0,20
FontColor=#colorText#
FontFace=#fontName#
FontSize=#textSize#
AntiAlias=1
ClipString=1
W=190
H=15

[styleRightText]
; Meters using styleRightText will be right-aligned.
StringAlign=Right
StringCase=None
StringStyle=Bold
StringEffect=Shadow
FontEffectColor=0,0,0,20
FontColor=#colorText#
FontFace=#fontName#
FontSize=#textSize#
AntiAlias=1
ClipString=1
W=190
H=15

[styleCenterText]
; Meters using styleCenterText will be center-aligned.
StringAlign=Center
StringCase=None
StringStyle=Bold
StringEffect=Shadow
FontEffectColor=0,0,0,20
FontColor=#colorText#
FontFace=#fontName#
FontSize=#textSize#
AntiAlias=1
ClipString=1
W=190
H=15

[styleBar]
BarColor=#colorLine#
BarOrientation=Horizontal
SolidColor=69,69,69,15
W=190
H=#heightBar#

[styleLine]
LineCount=1
LineColor=#colorLine#
AntiAlias=1
GraphStart=Left
W=190
H=25

[styleSeperator]
SolidColor=69,69,69,15
W=190
H=#heightBar#
